### ISSUE TITLE
omiagent segfault libnss_files on Linux (scx provider)

### ISSUE THREAD

**Issue by johanburati** [microsoft/SCXcore#117]
omiagent is crashing with messages like these:
```
Sep  6 11:01:34 hostname kernel: omiagent[44104]: segfault at 7f7c6bc3fe00 ip 00007f7c6bc3fe00 sp 00007f7c69ce4d50 error 14 in libnss_files-2.17.so[7f7c6bdc7000+c000]
Sep  6 11:31:34 hostname kernel: omiagent[60927]: segfault at 7f5309121e00 ip 00007f5309121e00 sp 00007f5303107d50 error 14 in libnss_files-2.17.so[7f53092a9000+c000]
```

Environment information:
* OMS Agent:  1.7.9
* OMI omi-1.5.0-0
* SCX 1.6.3-659
* Distro: Red Hat Enterprise Linux Server release 7.5 (Maipo)

got a core file, could confirm the crash occurs in  /lib64/libnss_dns.so.2:

```
#0  0x00007f737fa78e00 in ?? ()
#1  0x00007f737fabcf47 in ?? ()
#2  0x00007f737fabcb60 in ?? ()
#3  0xffffffff00000073 in ?? ()
#4  0x0000000000000000 in ?? ()

From                To                  Syms Read   Shared Object Library
0x00007f738a0e08b0  0x00007f738a0ebe01  Yes (*)     /lib64/libpthread.so.0
0x00007f7389ed7d90  0x00007f7389ed888e  Yes (*)     /lib64/libdl.so.2
0x00007f7389cca620  0x00007f7389cd1cba  Yes (*)     /lib64/libpam.so.0
0x00007f7389a71b00  0x00007f7389aad4ed  Yes (*)     /opt/omi/lib/libssl.so.1.0.0
0x00007f7389662f00  0x00007f738979ac37  Yes (*)     /opt/omi/lib/libcrypto.so.1.0.0
0x00007f73892488d0  0x00007f738939822f  Yes (*)     /lib64/libc.so.6
0x00007f738a2f7ad0  0x00007f738a313080  Yes (*)     /lib64/ld-linux-x86-64.so.2
0x00007f7389003240  0x00007f73890097f2  Yes (*)     /lib64/libaudit.so.1
0x00007f7388dbf060  0x00007f7388df150a  Yes (*)     /lib64/libgssapi_krb5.so.2
0x00007f7388af0910  0x00007f7388b57cea  Yes (*)     /lib64/libkrb5.so.3
0x00007f73888c8500  0x00007f73888c90d3  Yes (*)     /lib64/libcom_err.so.2
0x00007f7388698890  0x00007f73886b6b4f  Yes (*)     /lib64/libk5crypto.so.3
0x00007f7388480170  0x00007f738848c6f8  Yes (*)     /lib64/libz.so.1
0x00007f7388279580  0x00007f738827b3bc  Yes (*)     /lib64/libcap-ng.so.0
0x00007f738806d720  0x00007f73880742bb  Yes (*)     /lib64/libkrb5support.so.0
0x00007f7387e675b0  0x00007f7387e681cc  Yes (*)     /lib64/libkeyutils.so.1
0x00007f7387c508f0  0x00007f7387c5ee92  Yes (*)     /lib64/libresolv.so.2
0x00007f7387a2c9d0  0x00007f7387a427d6  Yes (*)     /lib64/libselinux.so.1
0x00007f73877c55f0  0x00007f738780b5b0  Yes (*)     /lib64/libpcre.so.1
0x00007f738737ec00  0x00007f73874dc898  Yes (*)     /opt/omi/lib/libSCXCoreProviderModule.so
0x00007f738a3afcc0  0x00007f738a3cb568  Yes (*)     /opt/omi/lib/libmicxx.so
0x00007f7387026db0  0x00007f738702bc6c  Yes (*)     /lib64/libcrypt.so.1
0x00007f7386e201e0  0x00007f7386e2316c  Yes (*)     /lib64/librt.so.1
0x00007f7386b72220  0x00007f7386bd937a  Yes (*)     /lib64/libstdc++.so.6
0x00007f738681a310  0x00007f73868852d6  Yes (*)     /lib64/libm.so.6
0x00007f7386601a90  0x00007f7386611245  Yes (*)     /lib64/libgcc_s.so.1
0x00007f73863fcb40  0x00007f73863fd1bb  Yes (*)     /lib64/libfreebl3.so
0x00007f737fcc2130  0x00007f737fcc9481  Yes (*)     /lib64/libnss_files.so.2
0x00007f737ef762e0  0x00007f737efa531f  Yes (*)     /lib64/libssl3.so
0x00007f737ed4c2c0  0x00007f737ed60d97  Yes (*)     /lib64/libsmime3.so
0x00007f737ea2fdf0  0x00007f737eb04e24  Yes (*)     /lib64/libnss3.so
0x00007f737e7f38d0  0x00007f737e8035d8  Yes (*)     /lib64/libnssutil3.so
0x00007f737e5e3ec0  0x00007f737e5e4c28  Yes (*)     /lib64/libplds4.so
0x00007f737e3df4b0  0x00007f737e3e0b16  Yes (*)     /lib64/libplc4.so
0x00007f737e1acc30  0x00007f737e1cceaf  Yes (*)     /lib64/libnspr4.so
0x00007f737c116020  0x00007f737c11987f  Yes (*)     /lib64/libnss_dns.so.2
0x00007f735fdc6280  0x00007f735fdeffac  Yes (*)     /lib64/libsoftokn3.so
0x00007f735fb17a00  0x00007f735fb9f7e0  Yes (*)     /lib64/libsqlite3.so.0
0x00007f735f887600  0x00007f735f8e5a6d  Yes (*)     /lib64/libfreeblpriv3.so
0x00007f735f681c70  0x00007f735f68236b  Yes (*)     /lib64/libnsssysinit.so
0x00007f735f45a7e0  0x00007f735f4747c2  Yes (*)     /lib64/libnsspem.so
```

**Comment by JumpingYang001** [comment]
same with https://github.com/microsoft/omi/issues/641, close.
